#项目名称配置
spring:
  application:
    name: bootAdmin

  datasource:
    #连接MySql
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/jerveen?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    #Druid连接配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select now()
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    keepAlive: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j2
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

#MyBatis
mybatis:
  #配置映射文件位置
  mapper-locations: classpath:mapper/*Mapper.xml
  #实体类扫描配置
  type-aliases-package: com.jay.boot.model
  configuration:
    #开启驼峰命名法
    map-underscore-to-camel-case: true

#logback日志配置
logging:
  config:
    classpath: logback-spring.xml
  level:
    com:
      jay:
        boot:
          mapper: debug
